
/* ----------------------- µ°∏bäa ---------------------- */

#define ST_NO 1
#define ST_NAME 2
#define ST_SEX 3
#define ST_RESI 4
#define ST_BIRTH 5
#define ST_SOLAR 6
#define ST_ENROLLED 7
#define ST_GRADE 8
#define ST_CLASS 9
#define ST_ABSENCE 10
#define ST_MILITARY 11
#define ST_SCHOOL 12
#define ST_ZIP1 13
#define ST_AREA1 14
#define ST_TEL1 15
#define ST_ADDR1 16
#define ST_ZIP2 17
#define ST_AREA2 18
#define ST_TEL2 19
#define ST_ADDR2 20
#define GR_NO 21
#define GR_NAME 22
#define GR_SEX 23
#define GR_RESI 24
#define GR_BIRTH 25
#define GR_SOLAR 26
#define GR_GRADE 27
#define GR_COURSE 28
#define GR_ABSENCE 29
#define GR_MILITARY 30
#define GR_SEC 31
#define GR_SCHOOL 32
#define GR_COLLEGE 33
#define GR_ZIP1 34
#define GR_AREA1 35
#define GR_TEL1 36
#define GR_ADDR1 37
#define GR_ZIP2 38
#define GR_AREA2 39
#define GR_TEL2 40
#define GR_ADDR2 41
#define PART_NO 42
#define PART_NAME 43
#define DUTY_NO 44
#define DUTY_NAME 45
#define COMPANY_NO 46
#define COMPANY_NAME 47
#define LAB_NO 48
#define LAB_PROFESSOR 49
#define LAB_NOTE 50

#define STUDENTS 0
#define GRADUATES 1
#define PARTS 2
#define DUTIES 3
#define COMPANIES 4
#define LABS 5

